// tslint:disable:object-literal-sort-keys
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { map } from 'rxjs/operators';

import { nullProject, Project } from './projects';

@Injectable({ providedIn: 'root' })
export class ProjectsService {
  private readonly projects: Project[] = [
    {
      id: 81,
      date: 1568565360000,
      title: 'Quality Report',
      uri: 'quality-report',
      location: 'Detroit, MI',
      url: 'https://quality-report.qlms.foc.zone',
      image: 'quality-report.jpg',
      description: 'I built Quality Report to increase visibility into our code quality. It helps keep track of code coverage and other health metrics across all of our projects within Quicken Loans.',
      company: 'Quality Report is a home grown tool developed for Quicken Loans.',
      skills: ['Angular', 'RxJS', 'TypeScript', 'SonarQube', 'Spark'],
    },
    {
      id: 80,
      date: 1565886960000,
      title: 'Shipyard',
      uri: 'shipyard',
      location: 'Detroit, MI',
      url: 'https://shipyard.qlms.foc.zone',
      image: 'shipyard.jpg',
      description: 'I built Shipyard to help automate our code release workflow. It helps keep track of changes due for beta or production, and enables easy creation of release branches and tags.',
      company: 'Shipyard is a home grown tool developed for Quicken Loans.',
      skills: ['Angular', 'RxJS', 'TypeScript', 'Git', 'Spark'],
    },
    {
      id: 79,
      date: 1564677360000,
      title: 'Pricing Calculator',
      uri: 'pricing-calculator',
      location: 'Charlotte, NC',
      url: 'https://pricing-calc.apps.qlmortgageservices.com',
      image: 'pricing-calculator.jpg',
      description: 'This is a greenfield project I built from the ground up using an Angular frontend and a Node/TypeScript backend. I followed contract-first development principals. It uses DynamoDB and AWS Fargate.',
      company: 'This is the Pricing Calculator microsite that lives within the QLMS Partner Portal user experience. Quicken Loans Mortgage Services (QLMS) is the wholesale division of Quicken Loans.',
      skills: ['Angular', 'RxJS', 'Node', 'TypeScript', 'DynamoDB'],
    },
    {
      id: 78,
      date: 1537115760000,
      title: 'QLMS Partner Portal',
      uri: 'qlms-partner-portal',
      location: 'Charlotte, NC',
      url: 'https://portal.qlmortgageservices.com',
      image: 'qlms-partner-portal.jpg',
      description: 'I help manage everything for the QLMS Partner Portal including feature development, code reviews, and more. It\'s an AngularJS application with a PHP/Silex API.',
      company: 'Quicken Loans Mortgage Services (QLMS) is the wholesale division of Quicken Loans. We work directly with our partners to originate mortgage loans for their clients.',
      skills: ['PHP7', 'MySQL', 'Redis', 'Docker', 'RAML', 'CircleCI', 'AngularJS'],
    },
    {
      id: 77,
      date: 1487266560000,
      title: 'That\'s My Mortgage',
      uri: 'thats-my-mortgage',
      location: 'Charlotte, NC',
      url: 'https://www.thatsmymortgage.com',
      image: 'thats-my-mortgage.jpg',
      description: 'I did mostly feature-level work for an existing application. I Dockerized the application and worked on a custom PHP framework.',
      company: 'This is the client-facing application for Quicken Loans Mortgage Services (QLMS). QLMS is the wholesale division of Quicken Loans.',
      skills: ['PHP5', 'Redis', 'Docker'],
    },
    {
      id: 76,
      date: 1457199360000,
      title: 'Neco',
      uri: 'neco',
      location: 'Charlotte, NC',
      url: 'http://necowebs.com',
      image: 'neco.jpg',
      description: 'I did everything for this site, including design, development, infrastructure, and everything in between. The UI was written in Angular, while the API was written in PHP with Silex.',
      company: 'Neco is a Charlotte-based web design and development firm. I started this business essentially as a holding company for my personal/freelance work.',
      skills: ['PHP7', 'Silex', 'MariaDB', 'TypeScript', 'Angular'],
    },
    {
      id: 75,
      date: 1452038400000,
      title: 'Inside Chick-fil-A',
      uri: 'inside-chick-fil-a',
      location: 'Atlanta, GA',
      url: 'http://inside.chick-fil-a.com',
      image: 'inside-chick-fil-a.jpg',
      description: 'I helped maintain and develop new functionality for the Inside Chick-fil-A website. Development ranged from simple updates to integration and customization of third-party plugins for WordPress.',
      company: 'Atlanta-based Chick-fil-A, Inc. is a family owned and privately held restaurant company devoted to serving the local communities in which its restaurants operate. Known for its original chicken sandwich and unique franchise model, Chick-fil-A serves freshly prepared food in more than 1,900 restaurants in 42 states and Washington, D.C.',
      skills: ['PHP5', 'MySQL', 'JavaScript', 'jQuery', 'WordPress'],
    },
    {
      id: 74,
      date: 1436213580000,
      title: 'Advance America',
      uri: 'advance-america',
      location: 'Spartanburg, SC',
      url: 'https://www.advanceamerica.net/',
      image: 'advanceamerica.jpg',
      description: 'I helped create and manage the back-end for the website. The site utilizes the CodeIgniter framework integrated with an Oracle database which required in depth modifications. There are administrative tools in a custom content management area that I helped write as well.',
      company: 'As a nationally-recognized, fully-accredited financial company, we help millions of people every year with our financial services.Since 1997, we\'ve helped millions of Americans with flexible and personalized financial solutions. We\'ve grown from just a few centers in the Southeast United States to become one of the nation\'s largest consumer lending companies, with more than 2,400 locations offering a variety of financial services. Advance America is a wholly owned subsidiary of Grupo Elektra, one of the world\'s leading providers of banking services, consumer finance and specialty retailing. We comply with all federal and state laws and always present fees clearly and completely. We are also proud to be a founding member of the Community Financial Services Association, which encourages fair and fully disclosed lending practices. So you can rest easy knowing you\'ve made a smart choice with Advance America.',
      skills: ['PHP5', 'Oracle Database 12c', 'CodeIgniter', 'Content Management'],
    },
    {
      id: 73,
      date: 1436213580000,
      title: 'National Cash Advance',
      uri: 'national-cash-advance',
      location: 'Spartanburg, SC',
      url: 'https://www.nationalcashadvance.com/',
      image: 'nationalcashadvance.jpg',
      description: 'I helped create and manage the back-end for the website. The site utilizes the CodeIgniter framework integrated with an Oracle database which required in depth modifications. There are administrative tools in a custom content management area that I helped write as well.',
      company: 'Founded in 1994, National Cash Advance is one of the nation\'s leading payday advance companies. We offer a quick, hassle free solution which can be a sensible alternative to credit card late charges or bank penalties for insufficient funds. Our professional staff provides one-on-one assistance to provide the money you need.',
      skills: ['PHP5', 'Oracle Database 12c', 'CodeIgniter', 'Content Management'],
    },
    {
      id: 72,
      date: 1436213340000,
      title: 'Purpose Financial Services',
      uri: 'purpose-financial-services',
      location: 'Spartanburg, SC',
      url: 'https://www.purposefinancialservices.com/',
      image: 'purposefinancialservices.jpg',
      description: 'I helped create and manage the back-end for the website. The site utilizes the CodeIgniter framework integrated with an Oracle database which required in depth modifications. There are administrative tools in a custom content management area that I helped write as well.',
      company: 'We offer a wide range of fast and convenient services* including cash advances, MoneyGram services, tax services and title loans. Since 1997, millions of customers have trusted us to provide financial solutions to meet their needs.',
      skills: ['PHP5', 'Oracle Database 12c', 'CodeIgniter', 'Content Management'],
    },
    {
      id: 71,
      date: 1433621100000,
      title: 'Denny\'s Denny\'s',
      uri: 'dennys-dennys',
      location: 'Spartanburg, SC',
      url: 'https://www.dennysdennys.com/',
      image: 'dennysdennys.jpg',
      description: 'I did the back-end work for the main Denny\'s Denny\'s website which included a sweepstakes entry form and back-end tool for viewing statistics and picking a winner. Additionally, there was an API that I helped develop which interfaced with a mobile app used at Nascar races across the country to superimpose fan\'s photos with a photo of Denny Hamlin.',
      company: 'Denny\'s is America\'s diner. This is where guests have come for over 60 years now to sit back, relax and enjoy delicious, hearty meals 24/7, every day of the year. From breakfast anytime to satisfying lunches and dinners, if you\'re in the mood for it, chances are we\'re serving it. Denny\'s is always open, always welcoming and always serving up hearty diner food along with a mug of fresh hot coffee. So come on in anytime, park yourself in a comfortable booth, take a seat at the counter, whatever you want, because it won\'t take you long to understand why we\'re truly America\'s diner.',
      skills: ['PHP', 'MySQL', 'JavaScript', 'jQuery', 'JSON', 'API Development'],
    },
    {
      id: 70,
      date: 1430942520000,
      title: 'Evolve USA',
      uri: 'evolve-usa',
      location: 'Greenville, SC',
      url: 'http://www.evolveusa.com/',
      image: 'evolveusa.jpg',
      description: 'I helped update the site with new articles and clean up database issues left over from a previous developer.',
      company: 'We believe we can all talk about guns without fighting. We do it by saying stuff like "Don\'t forget the safety!" and "Are your husband\'s guns locked up?" And we can all agree those aren\'t fightin\' words. Even if we don\'t agree on much else.',
      skills: ['PHP5', 'MySQL'],
    },
    {
      id: 69,
      date: 1423255920000,
      title: 'NFL House API',
      uri: 'nfl-house-api',
      location: 'Greenville, SC',
      url: 'http://api.nflhouse.com.epqa.us/',
      image: 'nflhouse.jpg',
      description: 'I wrote the API that both the NFL House mobile app and the administration app interfaced with. For example, users could order drinks on their mobile phone, my API would take the order and store it, as well as pass it on to the administrator\'s to fulfill the order. The API is written in PHP using Flight, an extensible micro-framework for PHP.',
      company: 'Verizon Super Bowl Central will be the hub of fan, sponsor, media and NFL activities for the five (5) days leading up to Super Bowl XLIX',
      skills: ['PHP5', 'MySQL', 'JSON', 'Flight'],
    },
    {
      id: 68,
      date: 1420577220000,
      title: 'Anytime Wallet',
      uri: 'anytime-wallet',
      location: 'Spartanburg, SC',
      url: 'https://www.anytimewallet.com/',
      image: 'anytimewallet.jpg',
      description: 'I did the back-end for the website, including the security, user management, account center, and interfacing with various private API\'s.',
      company: 'Anytime Wallet is your one-stop money source. We make getting money simple, quick and easy.That\'s why we\'re an online company, and we have helpful, friendly customer service representatives available and ready to help you at our contact center.',
      skills: ['PHP5', 'Oracle Database 12c', 'API', 'SOAP', 'XML'],
    },
    {
      id: 67,
      date: 1402083780000,
      title: 'Express Check Advance',
      uri: 'express-check-advance',
      location: 'Spartanburg, SC',
      url: 'https://www.expresscheckadvance.com/',
      image: 'expresscheckadvance.jpg',
      description: 'This website is built with PHP and MySQL in a CodeIgniter/MVC framework. It utilized technology I wrote to locate centers within a certain radius of a given address or zip code.',
      company: 'Formed in 1998, Express Check Advance is a leading financial services company located throughout Alabama, Mississippi, Louisiana, Kentucky and Virginia. With over 100 locations, Express Check Advance offers a variety of financial services including cash advances, title loans and tax services.',
      skills: ['PHP5', 'MySQL', 'CodeIgniter', 'Math/Geometry'],
    },
    {
      id: 66,
      date: 1396813200000,
      title: 'Denny\'s',
      uri: 'dennys',
      location: 'Spartanburg, SC',
      url: 'http://www.dennys.com.epqa.us/',
      image: 'dennys.jpg',
      description: 'I helped migrate the Denny\'s website from a previous developer. I helped our company take control seamlessly with very little bumps and bruises. The site is written with PHP/MySQL and utilizes ExpressionEngine for the content management.',
      company: 'Denny\'s is America\'s diner. This is where guests have come for over 60 years now to sit back, relax and enjoy delicious, hearty meals 24/7, every day of the year. From breakfast anytime to satisfying lunches and dinners, if you\'re in the mood for it, chances are we\'re serving it. Denny\'s is always open, always welcoming and always serving up hearty diner food along with a mug of fresh hot coffee. So come on in anytime, park yourself in a comfortable booth, take a seat at the counter, whatever you want, because it won\'t take you long to understand why we\'re truly America\'s diner.',
      skills: ['PHP', 'MySQL', 'ExpressionEngine'],
    },
    {
      id: 65,
      date: 1394138160000,
      title: 'Denny\'s Rorschach Toast Test',
      uri: 'dennys-rorschach-toast-test',
      location: 'Spartanburg, SC',
      url: 'http://www.frenchtoasttest.com.epqa.us/',
      image: 'frenchtoasttest.jpg',
      description: 'The Rorschach Toast Test site gives users some fun questions to answer regarding the toast on their screen. Based on their answers, a suggested french toast order is given at the end.',
      company: 'Denny\'s is America\'s diner. This is where guests have come for over 60 years now to sit back, relax and enjoy delicious, hearty meals 24/7, every day of the year. From breakfast anytime to satisfying lunches and dinners, if you\'re in the mood for it, chances are we\'re serving it. Denny\'s is always open, always welcoming and always serving up hearty diner food along with a mug of fresh hot coffee. So come on in anytime, park yourself in a comfortable booth, take a seat at the counter, whatever you want, because it won\'t take you long to understand why we\'re truly America\'s diner.',
      skills: ['PHP5', 'MySQL', 'JavaScript', 'jQuery', 'JSON'],
    },
    {
      id: 64,
      date: 1389040560000,
      title: 'Go With Purpose',
      uri: 'go-with-purpose',
      location: 'Spartanburg, SC',
      url: 'https://www.gowithpurpose.com/',
      image: 'gowithpurpose.jpg',
      description: 'This website is connected via API\'s to the Advance America suite of websites. It also utilized NetSpend technology. I worked mostly on the back-end integration.',
      company: 'Life moves fast. Some days there\'s barely enough time to manage your schedule let alone manage your budget. That\'s where your Purpose Card can help. It is a reloadable card you can use everywhere Visa debit cards are accepted.',
      skills: ['PHP5', 'MySQL', 'JavaScript', 'jQuery', 'JSON'],
    },
    {
      id: 63,
      date: 1386361620000,
      title: 'You Might Be Surprised',
      uri: 'you-might-be-surprised',
      location: 'Spartanburg, SC',
      url: 'https://www.advanceamerica.net/',
      image: 'youmightbesurprised.jpg',
      description: 'This website utilizes an in-house API we call "Pulse" that hits Twitter and checks for specific keywords being talked about regarding money, debt and more. We then translate that data into real-time statistics to show what exactly is on people\'s minds across the country at any given time.',
      company: 'Founded in 1997, Advance America offers a wide range of fast and convenient financial services at more than 2,400 locations nationwide.As the largest payday advance provider, we\'ve learned that there are a lot of misconceptions about payday loans from how much they cost to the people who use them. But you might be surprised to learn that many of these misconceptions are simply not true',
      skills: ['PHP5', 'MySQL', 'JavaScript', 'jQuery', 'AJAX', 'XML'],
    },
    {
      id: 62,
      date: 1383769140000,
      title: 'Denny\'s Roastometer',
      uri: 'dennys-roastometer',
      location: 'Spartanburg, SC',
      url: 'http://www.dennysroastometer.com.epqa.us/',
      image: 'dennysroastometer.jpg',
      description: 'I wrote the back-end functionality for the website. It is platform agnostic, working entirely off of the jQuery JavaScript framework. It utilizes AJAX to provide questions for the user to answer. Then, after answering several questions, provides the user with a suggestion which roast of coffee is right for them.',
      company: 'Denny\'s is America\'s diner. This is where guests have come for over 60 years now to sit back, relax and enjoy delicious, hearty meals 24/7, every day of the year. From breakfast anytime to satisfying lunches and dinners, if you\'re in the mood for it, chances are we\'re serving it. Denny\'s is always open, always welcoming and always serving up hearty diner food along with a mug of fresh hot coffee. So come on in anytime, park yourself in a comfortable booth, take a seat at the counter, whatever you want, because it won\'t take you long to understand why we\'re truly America\'s diner.',
      skills: ['JavaScript', 'jQuery', 'XML', 'AJAX'],
    },
    {
      id: 61,
      date: 1378494900000,
      title: 'Hobbit Contest - Denny\'s',
      uri: 'hobbit-contest-dennys',
      location: 'Spartanburg, SC',
      url: 'http://hobbit.dennys.com.epqa.us/',
      image: 'dennyshobbit.jpg',
      description: 'I helped in a minor capacity with the front-end of the website. My main focus was the back-end, and sweepstakes functionality.',
      company: 'Denny\'s is America\'s diner. This is where guests have come for over 60 years now to sit back, relax and enjoy delicious, hearty meals 24/7, every day of the year. From breakfast anytime to satisfying lunches and dinners, if you\'re in the mood for it, chances are we\'re serving it. Denny\'s is always open, always welcoming and always serving up hearty diner food along with a mug of fresh hot coffee. So come on in anytime, park yourself in a comfortable booth, take a seat at the counter, whatever you want, because it won\'t take you long to understand why we\'re truly America\'s diner.',
      skills: ['PHP5', 'MySQL', 'HTML5', 'CSS3'],
    },
    {
      id: 60,
      date: 1370545920000,
      title: 'Give Them a Shot',
      uri: 'give-them-a-shot',
      location: 'Detroit, MI',
      url: 'http://www.givethemashot.org.epqa.us/',
      image: 'givethemashot.jpg',
      description: 'I managed the server and back-end for this site. This included a minor MySQL database that hosted user details captured from a form on the front page.',
      company: 'Making it in today\'s world is tough. But at the Jalen Rose Leadership Academy (JRLA), we\'re giving Detroit\'s kids a better shot at success in life through our proven educational approach focused on preparing our students to succeed long after they graduate. Learn how you can make a difference and even get a shot at winning $10,000.',
      skills: ['PHP5', 'MySQL'],
    },
    {
      id: 59,
      date: 1360181160000,
      title: 'F-35',
      uri: 'f-35',
      location: 'Greenville, SC',
      url: 'https://www.f35.com/',
      image: 'f35.jpg',
      description: 'I helped with portions of the front-end for the F-35 website. I also manage their security certificate updates as well as minor server administration.',
      company: 'The F-35 Lightning II is a 5th Generation fighter, combining advanced stealth with fighter speed and agility, fully fused sensor information, network-enabled operations and advanced sustainment. Three variants of the F-35 will replace the A-10 and F-16 for the U.S. Air Force, the F/A-18 for the U.S. Navy, the F/A-18 and AV-8B Harrier for the U.S. Marine Corps, and a variety of fighters for at least ten other countries.',
      skills: ['LAMP', 'Content Management', 'Front-end'],
    },
    {
      id: 58,
      date: 1352232120000,
      title: 'Upstate SC Alliance',
      uri: 'upstate-sc-alliance',
      location: 'Greenville, SC',
      url: 'http://www.upstatescalliance.com/',
      image: 'upstatescalliance.jpg',
      description: 'This was a pre-existing website that I was tasked with updating. Updates included some minor front-end work and mostly content updates.',
      company: 'Formed in 2000, the Upstate South Carolina Alliance is a public/private regional economic development organization designed to market the dynamic 10-county Upstate region to the world. The 10 counties of the Alliance represent the commerce-rich northwestern corner of South Carolina.',
      skills: ['PHP', 'HTML', 'CSS'],
    },
    {
      id: 57,
      date: 1349116740000,
      title: 'I am a United Way Donor',
      uri: 'i-am-a-united-way-donor',
      location: 'Greenville, SC',
      url: 'http://www.iamaunitedwaydonor.com.epqa.us/',
      image: 'iamaunitedwaydonor.jpg',
      description: 'This website was to help increase donations to the United Way of Greenville County. Users could "purchase" an icon on the site for $1.00 and that icon would become theirs. You could click on icons that were previously purchased to see who purchased or purchase your own.',
      company: 'Bringing people and resources together to build a Cycle of Success, where: all children in Greenville County start school prepared to learn and go on to graduate; well educated graduates find good jobs and create stable homes; and children from stable homes continue the cycle because they start school on track and prepared for success.',
      skills: ['HTML5', 'CSS3', 'Responsive front-end', 'PHP5', 'MySQL'],
    },
    {
      id: 56,
      date: 1341115200000,
      title: 'Palmetto Christian Academy',
      uri: 'palmetto-christian-academy',
      location: 'Mount Pleasant, SC',
      url: 'http://www.palmettochristianacademy.org/',
      image: 'palmettochristianacademy.jpg',
      description: 'I worked on Palmetto Christian Academy\'s website from post-design to project completion. Based in Joomla 2.5, the website features custom components I built to help maintain Athletics, Events, FAQs, Opponents, and Photos. The blog is built in WordPress with a customized template to match the website\'s design.',
      company: 'As a covenant school, PCA exists to assist Christian parents in the discipleship of their children. All academic courses and co-curricular activities are designed to reveal God\'s truth and to train students in godly character. Our college preparatory, academic program is taught within a Christian world and life view. This Christ-centered program of study encourages all students to embrace the gospel of Jesus Christ and to address the implications of their faith in all of life.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 2.5', 'WordPress'],
    },
    {
      id: 55,
      date: 1341115200000,
      title: 'Hilton Head Presbyterian Church',
      uri: 'hilton-head-presbyterian-church',
      location: 'Hilton Head, SC',
      url: 'http://www.hiltonheadpca.com/',
      image: 'hiltonheadpca.jpg',
      description: 'I worked on Hilton Head Presbyterian Church\'s website from post-design to project completion. The main website is based in Joomla 2.5 and features custom components I built to help maintain Events, FAQs, Photos, and Sermons. The website also features a blog built in WordPress with a custom template to match the website\'s design.',
      company: 'We strive to communicate the love and good news of Christ to our neighbors both locally and around the world. We endeavor to widely cultivate a deepening faith in Christ through intentional relationships among fellow believers. We seek to equip those who attend Hilton Head Presbyterian Church with a deep understanding and practical application of the Bible.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 2.5', 'WordPress'],
    },
    {
      id: 54,
      date: 1341115200000,
      title: 'The Fairchilds',
      uri: 'the-fairchilds',
      location: 'Paris, France',
      url: 'http://www.thefairchildsmusic.com/',
      image: 'thefairchildsmusic.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'Cyril Niccolai could be termed a modern Renaissance man. An accomplished singer and songwriter, he has spent over a decade honing his skills in his chosen field of rock music. Contemporaneously, he studied medicine and law in university, engages in a variety of sports including tennis, golf and scuba diving, dabbles in still and video photography, has a keen interest in literature and art and is a self-confessed tech geek. The globe trotting foodie next aspires to run the New York City marathon, learn more foreign languages and keep challenging himself with new projects.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 53,
      date: 1341115200000,
      title: 'Corner Kitchen',
      uri: 'corner-kitchen',
      location: 'Asheville, NC',
      url: 'http://www.thecornerkitchen.com/',
      image: 'thecornerkitchen.jpg',
      description: 'I worked on The Corner Kitchen\'s website from post-design to project completion. The main website is based in Joomla 2.5 and features a custom shopping cart that I built. The shopping cart includes components to help manage products, product attributes, customers, orders, shipping methods, payment methods, and taxes. The cart also includes hooks into various API\'s including PayPal ExpressCheckout, PayPal DirectPayment, Authorize.net, and UPS. The website also features custom components to help maintain recipes and staff bios. The mobile website is powered by Joomla using custom components I built as well. The blog is built in WordPress and features a custom template that matches the website\'s design.',
      company: 'The day we opened the Corner Kitchen the house was one hundred and eight years old. George Washington Vanderbilt came to Asheville in the late 1880\'s and bought the 72 acres that ultimately became Biltmore Village.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 2.5', 'WordPress', 'Mobile Development'],
    },
    {
      id: 52,
      date: 1338523200000,
      title: 'Tuffaloy',
      uri: 'tuffaloy',
      location: 'Greer, SC',
      url: 'http://tuffaloy.com/',
      image: 'tuffaloy.jpg',
      description: 'I worked on Tuffaloy\'s website from post-design to project completion. The main website is based in Joomla 2.5 and features and extremely customized set of components to help maintain their products and part numbers. Each product page can contain multiple tables and each table can contain multiple parts and rows. The system is all set up to allow Tuffaloy to add new products, tables, and part numbers without any outside assistance. It is programmed to automatically create database tables. This is one of the most advanced websites I have built. The mobile website also makes use of these components as well as the mobile component that I built.',
      company: 'The little "TUFFALOY man" is now over seventy years old. It was in 1937 that Welding Sales & Engineering Company of Detroit introduced a new line of resistance welding alloys trade named TUFFALOY. Today this worldwide familiar name represents the most innovative and respected name in the field of resistance welding. Tuffaloy\'s products are used globally in industries such as transportation, appliances, office furniture, aerospace, construction, agriculture and many more.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 2.5', 'Mobile Development'],
    },
    {
      id: 51,
      date: 1338523200000,
      title: 'Tile Council of North America',
      uri: 'tile-council-of-north-america',
      location: 'Anderson, SC',
      url: 'http://www.tcnatile.com/',
      image: 'tcnatile.jpg',
      description: 'I worked on Tile Council of North America\'s website from post-design to project completion. The website is based in Joomla 2.5 and features a custom shopping cart that I built. The shopping cart includes components to help manage products, product attributes, customers, orders, shipping methods, payment methods, and taxes. There are also customizations to the shopping cart including a lab tests portion that is unique to TCNA. The cart also includes hooks into various API\'s including PayPal ExpressCheckout, PayPal DirectPayment, Authorize.net, and UPS. The website also features custom components to help manage emails, events, FAQs, published articles, and staff members.',
      company: 'Established in 1945 as the Tile Council of America (TCA), the Tile Council was created with the sole purpose of expanding the ceramic tile market in the United States. TCA\'s research laboratory has developed and patented many innovative installation materials which have improved ceramic tile installation.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 2.5'],
    },
    {
      id: 50,
      date: 1335844800000,
      title: 'United Way of Henderson County',
      uri: 'united-way-of-henderson-county',
      location: 'Hendersonville, NC',
      url: 'http://www.liveunitedhc.org/',
      image: 'liveunitedhc.jpg',
      description: 'I worked on United Way of Henderson County\'s website from post-design to project completion. The website is based in Joomla 2.5 and features custom components I built for maintaining Events, FAQs, and Photos.',
      company: 'UWHC works side-by-side with government, businesses and other community stakeholders to help solve Henderson County\'s most pressing issues. UWHC is the catalyst for community change by providing a neutral table, around which diverse groups can partner, collaborate and produce measurable results.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 2.5'],
    },
    {
      id: 49,
      date: 1335240000000,
      title: 'Hendersonville Lightning',
      uri: 'hendersonville-lightning',
      location: 'Hendersonville, NC',
      url: 'http://www.hendersonvillelightning.com/',
      image: 'hendersonvillelightning.jpg',
      description: 'I worked on Hendersonville Lightning\'s website from post-design to project completion. The main website is based in Joomla 2.5 and features custom components for Ad Banners, Classifieds, Communities, Emails, Events, Obituaries, and Photos. The mobile website is powered by Joomla using custom components I built as well. The website also features a shopping cart developed entirely by myself from the ground up. The shopping cart utilizes API\'s from UPS, PayPal, and Authorize.net. The blog is based in WordPress with a custom template that matches the website. This is one of the most advanced and feature-rich websites I\'ve built.',
      company: 'The Hendersonville Lightning and HendersonvilleLightning.com serves Henderson County with coverage of news, politics, public affairs, dining, entertainment and commentary.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 2.5', 'WordPress', 'Mobile Development'],
    },
    {
      id: 48,
      date: 1334808000000,
      title: 'Interfaith Assistance Ministry',
      uri: 'interfaith-assistance-ministry',
      location: 'Hendersonville, NC',
      url: 'http://www.iam-hc.org/',
      image: 'iamhc.jpg',
      description: 'I worked on Interfaith Assistance Ministries\' website from post-design to project completion. Based in Joomla 1.5, the website features a custom component I built for maintaining their list of Supporters. The home page also features a flash-like image cycler built entirely in JavaScript using jQuery.',
      company: 'Interfaith Assistance Ministry is a faith-based non-profit organization providing assistance to Henderson County residents for over 28 years.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 47,
      date: 1334203200000,
      title: 'HR 3798 Support the Egg Bill',
      uri: 'hr-3798-support-the-egg-bill',
      location: 'Alpharetta, GA',
      url: 'http://www.eggbill.com/',
      image: 'eggbill.jpg',
      description: 'I worked on Egg Bill\' website from post-design to project completion. Based in Joomla 2.5, the website features custom components I built for FAQs, Photos, Rep Emails, and Videos. The website was a project by United Egg Producers in support of the bill.',
      company: 'The bill will require egg farmers to essentially double the space allotted for 270 million hens in the U.S. and make other important animal welfare improvements during a tiered phase-in period that allows farmers time to make the investments in better housing, with the assurance that all will face the same requirements by the end of the phase-in period. It would provide a uniform, national standard for all egg farmers rather than a patchwork of cumbersome and complicated laws in every state. The federal legislation protects interstate egg commerce and provides the nation\'s egg farmers with a stable, clear future while ensuring consumers with an ample supply of economical eggs and a variety of choices.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 2.5'],
    },
    {
      id: 46,
      date: 1332993600000,
      title: 'Practice Smart',
      uri: 'practice-smart',
      location: 'Asheville, NC',
      url: 'http://www.ipracticesmart.com/',
      image: 'ipracticesmart.jpg',
      description: 'I worked on Practice Smart\'s website from post-design to project completion. Based in Joomla 1.7, the website features custom components I built for Courses, Daily Tips, e-Book Contacts, Emails, Events, Locations, and Workshops. The website also features my custom built shopping cart for Joomla 1.7-2.5. It also has a flash-like image cycler built entirely in JavaScript using jQuery with Nivo Slider. The blog is built in WordPress with a custom template that matches the website.',
      company: 'Alyssa graduated from Northwestern Health Sciences University in 2007 with a master\'s degree in oriental medicine. In 2008, she opened a private practice in North Carolina and transitioned it into a community clinic in 2009. Over the next three years she built, managed, practiced, and then sold her community clinic in 2012 to start her next dream, practicesmart.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.7', 'WordPress'],
    },
    {
      id: 45,
      date: 1330578000000,
      title: 'RWHA, P.C.',
      uri: 'rwha-p.c',
      location: 'McDonough, GA',
      url: 'http://www.rwhcpa.com/',
      image: 'rwhcpa.jpg',
      description: 'I worked on RWHA\'s website from post-design to project completion. The main website is based in Joomla 2.5 and the blog is based in WordPress. The mobile website is powered by Joomla using custom components I built.',
      company: 'Although our firm only dates back to the fall of 1991, our origins can be traced back much further. Our founding partner, Lewis Robinson, began his career in public accounting in the 1960s. After building and selling his interests in several firms, Lewis spent the 1980s in private practice. In the early 1990s, he was again bitten by the entrepreneurial bug. Starting with just himself and a part time staff member, the firm has steadily grown through the years and now is a recognized leader in our marketplace.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress', 'Mobile Development'],
    },
    {
      id: 44,
      date: 1328590800000,
      title: 'Duff, White & Turner, LLC',
      uri: 'duff-white-turner-llc',
      location: 'Columbia, SC',
      url: 'http://www.dwtlawfirm.com/',
      image: 'duffwhiteturner.jpg',
      description: 'I worked on Duff, White & Turner\'s website from post-design to project completion. Based in Joomla 1.7, the website features custom components I built for Attorneys, Events, and Practice Areas. On the front-end, the Attorneys and Practice Areas portions of the website work together dynamically.',
      company: 'Duff, White & Turner is more than a collection of attorneys - it is a family. The firm is made up of individuals with diverse backgrounds who, together, provide the knowledge and experience to serve an array of clients and their unique needs, ensuring that they are provided top-tier legal advice and service. From employment practices to litigation defense, DWT is capable of handling your legal needs.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 43,
      date: 1328072400000,
      title: 'The 25 Hour Day',
      uri: 'the-25-hour-day',
      location: 'Greenville, SC',
      url: 'http://www.the25hourday.com/',
      image: 'the25hourday.jpg',
      description: 'I worked on The 25 Hour Day\'s website from post-design to project completion. The main website is based in Joomla 2.5 and features custom components to help maintain user\'s calendars, goals, as well as the home page flash-like image slider. The shopping cart includes components to help manage products, product attributes, customers, orders, shipping methods, payment methods, and taxes. The website connects to Google\'s Calendar API and syncs data back and forth between the website and Google. This website features some of the more advanced jQuery and AJAX that I have worked on.',
      company: 'The 25 Hour Day isn\'t just a catchy title or an abstract concept, it is our commitment to helping you find an extra hour in every day! Here\'s how...Assume that you go to bed at 10pm and get up at 6am. Assume that you take 30 minutes of "bed" or "wake up" time on either side of your sleep. That leaves 15 hours to be productive in a day. If you can find just 4 minutes in each of those hours (one less story at the water cooler, one less walk to the copier, one less story you read online) you\'ve found 60 minutes and you have a 25 Hour Day!',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 2.5'],
    },
    {
      id: 42,
      date: 1325653200000,
      title: 'Southern Comfort Wear',
      uri: 'southern-comfort-wear',
      location: 'Hendersonville, NC',
      url: 'http://www.southerncomfortwear.com/',
      image: 'southerncomfortwear.jpg',
      description: 'I worked on Southern Comfort Wear\'s website from post-design to project completion. The website is based in Joomla 1.7 and features a custom shopping cart that I built. The shopping cart includes components to help manage products, product attributes, customers, orders, shipping methods, payment methods, and taxes. The cart also includes hooks into various API\'s including PayPal ExpressCheckout, PayPal DirectPayment, Authorize.net, and UPS.',
      company: 'Based in Hendersonville, North Carolina, Southern Comfort Wear was founded in 1995 by Dave and Nancy Green. Dave and Nancy have unparalleled experience working with the elderly and the disabled. Nancy worked in the nursing field for 13 years, specializing in Geriatrics. She understands first-hand the unique needs of the disabled, and why adaptive clothing can make all the difference in someone\'s quality of life.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.7'],
    },
    {
      id: 41,
      date: 1325394000000,
      title: 'Judith Nourse Seminars',
      uri: 'judith-nourse-seminars',
      location: 'Hendersonville, NC',
      url: 'http://www.judithnourseseminars.com/',
      image: 'judithnourse.jpg',
      description: 'I worked on Judith Nourse\'s Seminars website from post-design to project completion. The website is based in Joomla 1.7 and features a custom component built to help manage her seminars. Clients can sign up and pay with PayPal to attend the seminars.',
      company: 'A series of early cancer deaths in my family when I was in my teens and 20\'s underlies my ongoing quest to understand what causes illness and what supports wellness. My career path the past 25 years has been a progression of learning, practicing and teaching the several complementary healing modalities that have had the greatest impact on my own health and wellbeing.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 1.7'],
    },
    {
      id: 40,
      date: 1324357200000,
      title: 'Asheville Cabins of Willow Winds',
      uri: 'asheville-cabins-of-willow-winds',
      location: 'Asheville, NC',
      url: 'http://www.ashevillecabins.com/',
      image: 'ashevillecabins.jpg',
      description: 'I worked on Asheville Cabins\' website from post-design to project completion. The main website is based in Joomla 1.7 and features custom components I built for Activities, Amenities, Events, Guest Comments, Photos, Restaurants, and Rooms. The website also features a custom module that dynamically fades between guest comments. The blog is built in WordPress and features a customized template.',
      company: 'We were proud when ABC new named Asheville as one of the Ten Most Beautiful Places in America. We are also proud to say that we believe there is no vacation lodging in Asheville that is in a more beautiful setting than our 25 cabin rentals in our four Seasons woodland gardens. Our lodging continues to be surrounded with beauty after the peak leaf season, with our many shrubs and plantings that never lose their leaves or color.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.7', 'WordPress'],
    },
    {
      id: 39,
      date: 1322715600000,
      title: 'WHKP 1450 AM',
      uri: 'whkp-1450-am',
      location: 'Hendersonville, NC',
      url: 'http://www.whkp.com/',
      image: 'whkp.jpg',
      description: 'I worked on WHKP\'s website from post-design to project completion. Based in Joomla 1.7, the website features custom components I built for Birthdays and breaking news.',
      company: 'WHKP- Now in our 66th year of broadcasting serving the fine residents of Henderson County in the beautiful Blue Ridge Mountains of Western North Carolina in Hendersonville. Vist our website and listen live!',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.7'],
    },
    {
      id: 38,
      date: 1317441600000,
      title: 'Alien Ant Farm',
      uri: 'alien-ant-farm',
      location: 'Riverside, CA',
      url: 'http://alienantfarm.com/',
      image: 'alienantfarm.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'Alien Ant Farm is an American alternative rock band that formed in Riverside, California, United States, in 1995. Their name comes from an idea original guitarist Terry Corso had about aliens and the earth: "I was daydreaming at my dull desk job with my feet up, and I thought to myself, \'Wouldn\'t it be cool if the human species were placed on earth and cultivated by alien intelligence?\' Maybe the aliens added us to an atmosphere that was suitable for us, and they\'ve been watching us develop and colonize, kind of like what a kid does with an ant farm." The band has sold over 5 million units worldwide, and has four studio albums, and eight music videos.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 37,
      date: 1314849600000,
      title: 'Egypt Central',
      uri: 'egypt-central',
      location: 'Memphis, TN',
      url: 'http://www.egyptcentral.net/',
      image: 'egyptcentral.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'Egypt Central is an American Alternative metal band from Memphis, Tennessee.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 36,
      date: 1312171200000,
      title: '12 Stones',
      uri: '12-stones',
      location: 'Mandeville, LA',
      url: 'http://www.12stones.com/',
      image: '12stones.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: '12 Stones is a post-grunge band that was formed in 2000 in Mandeville, Louisiana. They have sold more than 2 million records.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 35,
      date: 1310616000000,
      title: 'LynxTo',
      uri: 'lynxto',
      location: 'Greenville, SC',
      url: 'http://www.lynxto.com/',
      image: 'lynxto.jpg',
      description: 'I worked on LynxTo\'s website and application from post-design to project completion. The main website is based in Joomla 1.5 and features a custom component that helps manage testimonials. The website also features a small shopping cart that allows users to purchase LynxTo accounts. The cart contains hooks to PayPal\'s API for their merchant accounts. The application itself which includes administration and mobile display is programmed entirely by me without use of any frameworks. The application allows users to pick which icons to display on their mobile page, configure settings for each icon such as Facebook URL, and then gives them a QR code to use on marketing materials. Users then scan the QR code and land on the mobile page with the icons that helps users connect with companies in a more friendly way. This is one of the most advanced applications that I have written.',
      company: 'When people see what is behind that once boring QR code, they start to realize that there is power in supplying options to your viewer, from informative and fun video, to specific web pages and profiles, to instant contact through phone and email, to instant "likes" and "follows" on your social networks, to quick donations, to...well you get the point. The options are only limited by your imagination (and the web).',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 34,
      date: 1309492800000,
      title: 'Chris Adler',
      uri: 'chris-adler',
      location: 'Richmond, VA',
      url: 'http://chris-adler.com/',
      image: 'chrisadler.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'Chris Adler is a drummer, best known as a member of Lamb of God. He is the older brother of bandmate and guitarist Willie Adler. Chris had played in several local bands before joining Lamb of God in 1994. He is known for his often used Heel-toe technique.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 33,
      date: 1308628800000,
      title: 'Wartown',
      uri: 'wartown',
      location: 'Warner Robins, GA',
      url: 'http://www.wartownonline.com/',
      image: 'wartownonline.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'WARTOWN is Steve Holcomb and Mike Yurgalavage, two long-time friends who have played music in one form or another for nearly 25 years. Formerly performing simply as "Steve and Mike", they have pushed themselves to grow and expand their shows, striving to increase their audiences and playing in new venues. The name WARTOWN is also the \'nickname\' of their home-town city, Warner Robins, Georgia. Their sound can best be described as \'Powered Acoustic\' and they strive to be a little different in their approach to music, especially the acoustic genre. Technically speaking, they are an \'acoustic duo\', but at one of their shows you will quickly realize that their sound is much bigger than you expected, with backing basslines, percussion, and various other instruments too numerous to count. It\'s hard to believe all of that sound and 4800 watts of energy is coming from only 2 people. With a performance list of over 100 songs, their palette of covers runs through a deep variety of artists and styles. Well known in the middle Georgia area for their fun and interactive performances, they have quickly become a staple of the Warner Robins music scene. You might hear them play anything from blues, country, rock, southern rock, pop, R&B, to hip hop (yes a \'Wartown\' form of acoustic hip-hop) that will be those songs that are very familiar to audiences, punctuated with surprise song combinations (Stain\'d mixed with Gnarls Barkley, Led Zeppelin mixed with Marshall Tucker, John Mayer mixed with Ludacris, etc.) that keep audiences looking and listening for more. Often playing for 3 or 4 hours with no breaks, their shows are a non-stop, musical experience not to be missed.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 32,
      date: 1302494400000,
      title: 'Palmetto Olive Oil',
      uri: 'palmetto-olive-oil',
      location: 'Greenville, SC',
      url: 'http://www.palmettooliveoilco.com/',
      image: 'palmettooliveoil.jpg',
      description: 'I worked on Palmetto Olive Oil\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features custom components I built to help manage testimonials and recipes. The website also features a custom shopping cart I built for Joomla 1.5 which contains connections to authorize.net\'s API for handling payments. The blog is built with WordPress and features a custom template that matches the website\'s design.',
      company: 'Palmetto Olive Oil Co., is locally owned and operated. It is the culmination of partners Charlotte & Michael Easler and Sandy & Michael Burn\'s love of good food, company of friends and family, and a desire to own their own business.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 31,
      date: 1301630400000,
      title: 'TOWN Magazine',
      uri: 'town-magazine',
      location: 'Greenville, SC',
      url: 'http://www.towncarolina.com/',
      image: 'townmagazine.jpg',
      description: 'I worked on TOWN Magazine\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features custom components I built for maintaining Restaurants, Events, and Locations. The blog is based in WordPress with a custom template that matches the website.',
      company: 'The pages of TOWN magazine capture the excitement of the Upcountry\'s grand experience. Its pages reflect the style, luxury and beauty of the entire area. TOWN strives to be the authority on living well in the Upstate, one of the fastest-growing areas in the Southeast. Through compelling articles, stylish design, and captivating photography, TOWN engages the reader with illuminating profiles and timely features on art, culture, fashion, along with a guide to the lively social scene. There\'s more. TOWN provides advertisers a credible, beautiful medium in which to place their advertisements-through print, website and signature events. TOWN is a must read for the educated, affluent, stylish and discerning consumers.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 30,
      date: 1299560400000,
      title: 'Extreme Country Stampede Tour',
      uri: 'extreme-country-stampede-tour',
      location: 'Nicholasville, KY',
      url: 'http://www.extremecountrytour.com/',
      image: 'extremecountrystampedetour.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'Extreme Country Stampede Tour was founded in 2010 by Kenny Churchill and Ryan Conley to provide inexpensive family entertainment to rural communities and cities alike. The objective is to provide consumers with several extreme sports events that are typically never performed together in one location, while generating a festival and family atmosphere which emphasizes country music and rodeo, also a monster truck show and even an extreme free-style motocross show. The organization consists of a small group of dedicated professionals that are experts in the fields of business, event management, and talent purchasing. Kenny and Ryan and thier staff are entering their partnership of offering a unique entertainment value to people across the nation. In previous year, events have attracted up to 20,000 people in one weekend and as the company\'s operations and popularity continue to expand, the opportunities for sponsors to exploit the different consumer markets of event participants will continue to grow. The Entertainment Industry as a whole is dictated by our economy. So we are taking some of the largest attractions in the world and putting them all together for one all day fun filled exciting event!!!',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 29,
      date: 1296536400000,
      title: 'WTZQ AM 1600',
      uri: 'wtzq-am-1600',
      location: 'Flat Rock, NC',
      url: 'http://www.wtzq.com/',
      image: 'wtzq.jpg',
      description: 'I worked on WTZQ\'s website from post-design to project completion. Based in Joomla 2.5, the website features a custom components I built to help maintain events.',
      company: 'George\'s radio career began in the early 1980s at WMUU in Greenville, SC. In 1991, he moved to Nashville where he eventually went to work for Tuned In Broadcasting. After stints in production, news, marketing & even a brief role as receptionist, George eventually became the co-host of the morning show on WRLT, Lightning 100.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 2.5'],
    },
    {
      id: 28,
      date: 1294030800000,
      title: 'Medley and Brown',
      uri: 'medley-and-brown',
      location: 'Jackson, MS',
      url: 'http://www.medleybrown.com/',
      image: 'medleybrown.jpg',
      description: 'I worked on Medley and Brown\'s website from post-design to project completion. The website is based in Joomla 1.5 and features a custom component I built to help manage testimonials.',
      company: 'Medley & Brown, LLC is a fee-only investment advisor that offers asset management services to individuals, families, small businesses, foundations, and retirement plans. Our goals are to preserve investor capital and achieve long-term appreciation in ways designed to minimize risk. Client assets are generally invested in no-load mutual funds. Investments are allocated among money market funds, U.S. common stocks, bonds, and international stocks for potential growth and safety of principal. Portfolios are generally $500,000 or more.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 27,
      date: 1292562000000,
      title: 'TransTech',
      uri: 'transtech',
      location: 'Piedmont, SC',
      url: 'http://www.transtech.com/',
      image: 'transtech.jpg',
      description: 'I worked on TransTech\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features custom components I built for maintaining Clients, Documents, Products, Sales Companies, and Sales Reps. The blog is based in WordPress with a custom template that matches the website.',
      company: 'TransTech has been Moving Electrification Forward for over 55 years specializing in electrical power transfer systems in the Transit and Industrial markets. From the beginning, our emphasis has been on superior product performance with a priority on delivering the most reliable solutions to meet each customer\'s electrical power transfer requirements.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 26,
      date: 1291957200000,
      title: 'aeSolutions',
      uri: 'aesolutions',
      location: 'Greenville, SC',
      url: 'http://www.aesolns.com/',
      image: 'aesolutions.jpg',
      description: 'I worked on aeSolutions\' website from post-design to project completion. Based in Joomla 1.5, the website features custom components I built for Documents, Products, Services, and Testimonials. The website also features an advanced multi-column navigation menu.',
      company: 'In business since 1998, aeSolutions is a complete supplier of performance-based process safety engineering and automation solutions. We utilize proven processes to help ensure consistent project execution and help customers optimize production, quality, and safety. We are committed to providing engineering services that enable our clients to sustainably own, operate, and maintain their process facilities.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 25,
      date: 1291698000000,
      title: 'Allison Development Group',
      uri: 'allison-development-group',
      location: 'Hendersonville, NC',
      url: 'http://www.allisondevelopmentgroup.com/',
      image: 'allisondevelopmentgroup.jpg',
      description: 'I worked on Allison Development Group\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features a custom component I built for their Portfolio. The Portfolio features advanced navigation that allows you to search by service, industry, or location. The blog is built in WordPress and features a customized template.',
      company: 'Erica McArthur Allison founded Allison Development Group in 2007, the culmination of many years working in real estate development, public relations and community facilitation. Her goal is simple: help clients develop their ideas, develop their messages and ultimately, develop their business. To accomplish that, Erica uses a combination of market research and analysis, social media applications, traditional media approaches and tried and true networks to get the people, places and projects she represents promoted in a very strategic and successful manner.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 24,
      date: 1290315600000,
      title: 'Lucid Grey',
      uri: 'lucid-grey',
      location: 'Lexington, KY',
      url: 'http://www.lucidgrey.com/',
      image: 'lucidgrey.jpg',
      description: 'This is one of the websites built in conjunction with dboy-designs that utilizes my custom content management system and social network I developed for bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'Lucid Grey, as you see it, culminated in 2003 in Lexington, KY. Through its earlier humble beginnings as a power trio, it evolved into a five piece. It developed with the contributions of past members until it became Greg, Blue, Clark, Justin, and Billy again in 2008. The chemistry was complete. The new era started.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 23,
      date: 1285905600000,
      title: 'Work & Play Trading Card Co.',
      uri: 'work-play-trading-card-co',
      location: 'Simpsonville, SC',
      url: 'http://www.workandplaytradingcards.com/',
      image: 'workandplaytradingcards.jpg',
      description: 'I worked on Work & Play Trading Card Company \'s website from post-design to project completion. The website is based in Joomla 1.5 and features custom components I built for maintaining Customers, Orders, and Products. These components work together with my custom built shopping cart that helps users create and purchase custom trading cards.',
      company: 'Work & Play Trading Card Company of Simpsonville, South Carolina, was established when the cards we made for our own kids were noticed by friends and family and requested for their kids. It\'s a company founded on a desire to mark the moments that pass us by too quickly and to make it possible for others to do the same.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 22,
      date: 1283313600000,
      title: 'Fabric Editions',
      uri: 'fabric-editions',
      location: 'Greenville, SC',
      url: 'http://www.fabriceditions.com/',
      image: 'fabriceditions.jpg',
      description: 'I worked on Fabric Editions\' website from post-design to project completion. The main portion of the website is based in Joomla 1.5 and features a component for Free Projects. The mobile website is managed completely from within Joomla using my fully customized mobile components. The wholesale portion of the website is a shopping cart created using CRE Loaded, which is built off of OS Commerce.',
      company: 'Fabric Editions, Inc. is a wholly owned subsidiary of Jaftex Corporation. Fabric Editions, Inc. has been in business since 1996 specializing in packaged fabrics known as "pre-cuts" and "kits" which are sold into the mass specialty markets.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5', 'CRE Loaded', 'Mobile Development'],
    },
    {
      id: 21,
      date: 1280635200000,
      title: 'The Village Playhouse',
      uri: 'the-village-playhouse',
      location: 'Mount Pleasant, SC',
      url: 'http://www.thevillageplayhouse.com/',
      image: 'thevillageplayhouse.jpg',
      description: 'I worked on The Village Playhouse\'s website from post-design to project completion. Based in Joomla 1.5, the website features custom components I built to help maintain their yearly shows.',
      company: 'The Village Playhouse and Repertory Company is now in the eleventh season of professional theatre East of the Cooper. What began in the summer of 2001 in a converted storefront next to a grocery store has become one of South Carolina\'s leading professional theatres, dramatically changing the cultural landscape of the lowcountry. We are proud of the more than 110 mainstage productions that have graced our stages since we opened our doors. Village Playhouse and Rep produces more than 150 nights of theatre each season. Under the leadership of founding Artistic Director Keely Enright and Managing Director Dave Reinwald, the Village currently welcomes more than 10,000 patrons into the Playhouse each year. The Village Playhouse and Repertory is a small professional 501 (c) 3 organization, a founding member of the League of Charleston Theatres a proud member of Theatre Communications Group-a national organization of professional theatres across America, as well as a member of the Charleston Metro Chamber of Commerce.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 20,
      date: 1279252800000,
      title: 'Gianni Panini',
      uri: 'gianni-panini',
      location: 'Asheville, NC',
      url: 'http://www.giannipanini.net/',
      image: 'giannipanini.jpg',
      description: 'I worked on Gianni Panini\'s website from post-design to project completion. Based in Joomla 1.5, the website features a very nice design that really helps show off what Joomla is capable of. The restaurants page features a photo gallery that utilizes a lightbox-like popup to display images.',
      company: 'Growing up in small-town Italy, good food was never hard to find -- partially because everyone\'s mother was the best cook in the world, but also because all of our meals - even quick lunches - were handmade from fresh ingredients. Things have changed a lot since then. With the hectic pace of life these days, it can be hard to make time to eat right when most good food is slow, and most fast food is hardly even food at all. And that\'s where I think my paninis can help - by providing a fresh, healthy option for hungry customers who want to eat well but don\'t have time for a fancy restaurant. Each panini is hand-crafted daily using ingredients that are always fresh, and locally sourced when available. So take a moment to savor the taste you\'ll only find where Old World crafstmanship accommodates the busy modern schedule -- right here at Gianni Panini.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 19,
      date: 1278648000000,
      title: 'Charleston Stage',
      uri: 'charleston-stage',
      location: 'Charleston, SC',
      url: 'http://www.charlestonstage.com/',
      image: 'charlestonstage.jpg',
      description: 'I worked on Charleston Stage\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features custom components I built for the home page\'s flash-like cycler and their database of previous and upcoming shows at the theatre. The blog is built in WordPress and features a customized template.',
      company: 'Charleston Stage, founded by Playwright Julian Wiles in 1978, is South Carolina\'s largest professional theatre company. At the Historic Dock Street Theatre, which has just recently undergone a $19 million renovation, Charleston Stage has presented over 150 productions and played to a collective audience of over one million strong. Charleston Stage employs 10 full-time staff members, guest artists, and scores of actors, dancers, singers and musicians and TheatreWings High School Apprentices.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.7', 'WordPress'],
    },
    {
      id: 18,
      date: 1277956800000,
      title: 'Custom CMS / Social Network for Bands',
      uri: 'custom-cms-social-network-for-bands',
      location: 'Nicholasville, KY',
      url: 'http://jneal.com/dboy/template/',
      image: 'customcmssocialnetworkforbands.jpg',
      description: 'I developed this entirely custom content management system and social network targetted towards bands and record labels. It contains administration capabilities for users, news, tour dates, music, pages, artist profiles, photos, videos, newsletters, newsletter emails, and advertisements. Users can sign up and set themselves as attending specific tour dates, or even participate by commenting on news, photos, videos, or any other items contained within the website. Users maintain profiles and can even become friends with other users. The website makes use of AJAX with the assistance of jQuery and JSON. It also contains custom RSS feeds for news, tour dates, music, pages, photos, and videos.',
      company: 'This project was for dboy-designs. dboy-designs is a firm that specializes in websites and designs for the entertainment industry, or more specifically, bands and record labels. They take my programming and put a beautiful face on it, and the end result is one amazing fully custom social network.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'RSS / XML'],
    },
    {
      id: 17,
      date: 1275364800000,
      title: 'Kolorful Kitchen',
      uri: 'kolorful-kitchen',
      location: 'Fletcher, NC',
      url: 'http://kolorfulkitchen.com/',
      image: 'kolorfulkitchen.jpg',
      description: 'I worked on Kolorful Kitchen\'s website from post-design to project completion. The main website is based in CRE Loaded, which is built off of OS Commerce. The blog is based in WordPress with a custom template that matches the website.',
      company: 'Thank you for shopping with us online. You can shop without creating an account. Some outdated browsers try and urge the surfer to create an account. However, if you use the latest version of Internet Explorer, Google Chrome, Mozilla Firefox, or Apple Safari, everything should work fine. Yes, the enamelware is very popular. Its nice to find a baking surface that is naturally non-stick, easy clean up, and dishwasher safe in a beautiful, bright and cheerful color to match your kitchen. Glad you came back to shop with us again!',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'CRE Loaded'],
    },
    {
      id: 16,
      date: 1275364800000,
      title: 'dboy-designs',
      uri: 'dboy-designs',
      location: 'Nicholasville, KY',
      url: 'http://www.dboy-designs.com/',
      image: 'dboydesigns.jpg',
      description: 'I built the back-end for dboy-designs\' website which features custom CMS features to allow for easily updating the portfolio. dboy-designs has been a long time client and has brought me many opportunities to work with amazing clients and on amazing projects. When working with dboy-designs, they always handle all of the design and cut-in and I work soley on the programming aspects of the websites.',
      company: 'dboy-designs is a full service design studio. Our design team has many years of experience working in the advertising/marketing field and are ready to take on any project and successfully market to our clients\' target demographic or core audience. We offer cross-platform solutions for web, e-commerce, social media and online campaigns. dboy-designs has worked with some of the most distinguished brands and our portfolio speaks for the high quality service we provide. We understand that our clients\' needs vary and are dedicated to their success.',
      skills: ['PHP', 'MySQL'],
    },
    {
      id: 15,
      date: 1273118400000,
      title: 'Pubmission',
      uri: 'pubmission',
      location: 'Hendersonville, NC',
      url: 'http://www.pubmission.com/',
      image: 'pubmission.jpg',
      description: 'I worked on Pubmission\'s website from post-design to project completion. The website is based in Joomla 1.5 and features tons of custom components I built for maintaining Advertising, Chat Messages, Reviews, Genres, Prices, Promos, Publishers, Top Publications, Submissions, Testimonials, and Writers. The website allows writers and publishers to sign up and make payments for certain services. Payments are handled via authorize.net making use of their API. This is a very intricate website and application that is one of the most advanced and feature-rich projects I have worked on.',
      company: 'I came up with the idea for Pubmission in 2008. I was staring blankly at a massive soul-sucking spreadsheet I\'d made to track all of the writing submissions I\'d sent out to publishers and agents over the past year.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 14,
      date: 1272686400000,
      title: 'Instigate Clothing Company',
      uri: 'instigate-clothing-company',
      location: 'Easley, SC',
      url: 'http://jneal.com/instigateclothing.com/',
      image: 'instigateclothing.jpg',
      description: 'I worked alone on Instigate Clothing Company\'s website, including both design and programming. The website is based in Joomla 1.5 and features custom components I built to help maintain Orders, Photos, and Products.',
      company: 'Instigate Clothing was founded in 2010 by Jimmy Chalton. The company remains a one-man team as Jimmy leads the design, production, and sales of all products. Jimmy started off touring the nation as vocalist in a popular rapcore band, sporting t-shirts from various clothing companies thanks to their sponsorships. After this experience, he decided to start up his own clothing company, and thus Instigate Clothing was born.',
      skills: ['Website Design', 'xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 13,
      date: 1272686400000,
      title: 'Blue Ridge Christian Academy',
      uri: 'blue-ridge-christian-academy',
      location: 'Landrum, SC',
      url: 'http://www.brca.us/',
      image: 'brca.jpg',
      description: 'I worked on Blue Ridge Christian Academy\'s website from post-design to project completion. Based in Joomla 1.5, the website features a custom component I built to help maintain testimonials. The home page also features a jQuery image cycler.',
      company: 'Blue Ridge Christian Academy is a private college preparatory school that is nestled at the foot of Glassy Mountain in Greenville County, South Carolina. Our K4, Kindergarten, Elementary, Middle and High School students hail from Landrum, Campobello, Taylors, Greer, Travelers Rest, Spartanburg, Greenville, and Marietta as well as Columbus and Tryon, NC . Our centrally located setting encourages outdoor settings for classroom and extra-curricular activities.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 12,
      date: 1271217600000,
      title: 'Henderson County Chamber',
      uri: 'henderson-county-chamber',
      location: 'Hendersonville, NC',
      url: 'http://www.hendersoncountychamber.org/',
      image: 'hendersoncountychamber.jpg',
      description: 'I worked on Henderson County Chamber\'s website from post-design to project completion. Based in Joomla 1.5, the website features a multi-column home page with many customized modules. The blog is built using WordPress and features a custom template to match the website design.',
      company: 'As a local business membership organization, boasting 1100+ members, the Chamber works to present one voice to build a healthy economy and improve the quality of life in Henderson County. Representing our members, the Chamber pursues its purpose through the development of business, the economy, community, human resources and public affairs.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 11,
      date: 1262322000000,
      title: 'Shannon Forest Christian School',
      uri: 'shannon-forest-christian-school',
      location: 'Greenville, SC',
      url: 'http://www.shannonforest.com/',
      image: 'shannonforest.jpg',
      description: 'I worked on Shannon Forest Christian School\'s website from post-design to project completion. Based in Joomla 1.5, the website features custom components I built for Donations as well as the home page jQuery image cycler.',
      company: 'The purpose of Shannon Forest Christian School (SFCS) is to support the Christian home and church by providing quality education from an evangelical, Biblical perspective in order to equip and challenge students to influence culture and society for Jesus Christ.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 10,
      date: 1262322000000,
      title: 'Studio eFabrics',
      uri: 'studio-efabrics',
      location: 'New York, NY',
      url: 'http://www.studioefabrics.com/',
      image: 'studioefabrics.jpg',
      description: 'I worked on Studio eFabrics\' website from post-design to project completion. The main website is based in CRE Loaded which is based off of OS Commerce. The blog is based in WordPress and features a custom template I built that matches the website\'s design.',
      company: 'We are committed to providing the highest quality 100% cotton fabrics in 43/44" widths. Our collections provide a wide range of themes, styles and colors and we are very fortunate to be working with talented designers whose fabric collections are exclusive to StudioeFabrics as well as the talents of our own in-house staff. We are committed to providing excellent customer service to those purchasing our fabrics and products and stand behind them 100%.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'CRE Loaded', 'WordPress'],
    },
    {
      id: 9,
      date: 1262322000000,
      title: 'The Journal Watchdog',
      uri: 'the-journal-watchdog',
      location: 'Greenville, SC',
      url: 'http://www.journalwatchdog.com/',
      image: 'journalwatchdog.jpg',
      description: 'I worked on The Journal Watchdog\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features tons of custom components I built for maintaining Salaries, Crime Rates, Court Dockets, Prisoner Statistics, Restaurant Insepections, and more. The blog is based in WordPress with a custom template that matches the website. The homepage incorporates many difference pieces including data from the blog making it one of the more advanced and feature-rich websites I\'ve built.',
      company: 'JournalWatchdog.com is owned by Community Journals, a media company based in Greenville, S.C. Community Journals publishes metropolitan community weekly newspapers in Greenville and Spartanburg, S.C. as well as AtHome magazine, Foodie, Behind the Counter and Gifts We Love. Other Journal Web sites include JournalHomes.com, upstatefoodie.com and behindthecounteronline.com The company prides itself in being with, for and about its home communities. It\'s not enough to write about what happens to people and places. Journal reporters work hard to explain why something has happened and how it will affect lives.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 8,
      date: 1262062800000,
      title: 'South Carolina Home Corporation',
      uri: 'south-carolina-home-corporation',
      location: 'Greenville, SC',
      url: 'http://www.southcarolinahomecorp.com/',
      image: 'schomecorp.jpg',
      description: 'I worked on South Carolina Home Corporation\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features real estate listings stored in a local MySQL database. Data is imported into the database nightly using programming using RETS (Real Estate Transaction Standard). I\'ve also built a very intricate intranet for the company that helps them manage Tickets, Contacts, Agent Profiles, and Documents. The intranet is one of the more advanced projects I have worked on.',
      company: 'SCHC is The Full-Service Home Sales, Marketing, Management and Leasing Company. We are Locally Owned and Operated. Our services are specifically designed to serve our clients\' needs in today\'s market. Our staff operates with the understanding that every client has individual goals driving their real estate decisions.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'AJAX', 'JSON', 'PHP', 'MySQL', 'MLS via RETS', 'Joomla 1.5', 'WordPress'],
    },
    {
      id: 7,
      date: 1254888000000,
      title: 'Toby\'s Mattress Superstore',
      uri: 'tobys-mattress-superstore',
      location: 'Hendersonville, NC',
      url: 'http://www.tobysmattresssuperstore.com/',
      image: 'tobysmattressoutlet.jpg',
      description: 'I worked on Toby\'s Mattress Superstore\'\'s website from post-design to project completion. The main website is based in Joomla 2.5.',
      company: 'Serving Western North Carolina as a family owned and operated business for the last 16 years, Toby\'s Mattress Superstore has grown to become the area leader in sales, service, unquestioned value, and top quality mattress brands. Owner Toby Jones finds the best deals for his customers and offers exclusive factory pricing from name brands such as Serta, Simmons, Tempur-pedic, Park Place and Comfortaire.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 2.5'],
    },
    {
      id: 6,
      date: 1254369600000,
      title: 'Applied Companies',
      uri: 'applied-companies',
      location: 'Valencia, CA',
      url: 'http://www.appliedcompanies.net/',
      image: 'appliedcompanies.jpg',
      description: 'I worked on Applied Companies\' website from post-design to project completion. The website is based in Joomla 1.5 and features an advanced template with varying width sidebars depending on content. The website also features an advanced mutli-level navigation menu.',
      company: 'Applied Companies has produced thousands of custom designed, military mobile ruggedized COTS and MIL-STD ECU for shelter and other rapid mobility battlefield electronic enclosure applications.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 5,
      date: 1250481600000,
      title: 'Hilton Head Christian Academy',
      uri: 'hilton-head-christian-academy',
      location: 'Hilton Head, SC',
      url: 'http://www.hhca.org/',
      image: 'hhca.jpg',
      description: 'I worked on Hilton Head Christian Academy\'s website from post-design to project completion. The website is based in Joomla 1.5 and features a custom built module that controls the home page\'s flash-like jQuery image cycler.',
      company: 'In partnership with the Christian family, the students of HHCA will mature in their faith, demonstrate Christian character, identify and develop their God-given talents, be academically and intellectually prepared to engage the world and thereby impact generations to the glory of God.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 4,
      date: 1243828800000,
      title: 'Mountain Inn & Suites',
      uri: 'mountain-inn-suites',
      location: 'Flat Rock, NC',
      url: 'http://www.mountaininnflatrock.com/',
      image: 'mountaininnandsuites.jpg',
      description: 'I worked on Mountain Inn & Suites\' website from post-design to project completion. The website is based in Joomla 1.5 and features a custom component I built to help manage testimonials.',
      company: 'The Mountain Inn & Suites is locally owned and operated. A popular destination for visitors to Asheville, Biltmore and the mountains of Western North Carolina, we are conveniently located just minutes from Hendersonville and historic Flat Rock.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
    {
      id: 3,
      date: 1241409600000,
      title: 'Greenville Home Search Online',
      uri: 'greenville-home-search-online',
      location: 'Greenville, SC',
      url: 'http://www.greenvillehomesearchonline.com/',
      image: 'greenvillehomesearchonline.jpg',
      description: 'I worked on Greenville Home Search Online\'s website from post-design to project completion. The main website is based in Joomla 1.5 and features real estate listings stored in a local MySQL database. Data is imported into the database nightly using programming using RETS (Real Estate Transaction Standard).',
      company: 'SCHC is The Full-Service Home Sales, Marketing, Management and Leasing Company. We are Locally Owned and Operated. Our services are specifically designed to serve our clients\' needs in today\'s market. Our staff operates with the understanding that every client has individual goals driving their real estate decisions.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'MLS via RETS', 'Joomla 1.5'],
    },
    {
      id: 2,
      date: 1241150400000,
      title: 'Town and Country Home Designs',
      uri: 'town-and-country-home-designs',
      location: 'Hendersonville, NC',
      url: 'http://www.townandcountryhomedesigns.com/',
      image: 'townandcountryhomedesigns.jpg',
      description: 'I worked on Town and Country Home Design\'s website from post-design to project completion. The website is based in CRE Loaded which is built from OS Commerce. It features customizations to help with purchasing the home designs.',
      company: 'Town & Country Home Designs is a residential design firm based in Hendersonville, North Carolina which specializes in single family home designs and stock plans for builders and homeowners, with a focus on sloping lots and mountain views.',
      skills: ['xHTML', 'CSS', 'JavaScript', 'jQuery', 'PHP', 'MySQL', 'CRE Loaded'],
    },
    {
      id: 1,
      date: 1240372800000,
      title: 'Henderson Oil',
      uri: 'henderson-oil',
      location: 'Hendersonville, NC',
      url: 'http://www.hendersonoil.com/',
      image: 'hendersonoil.jpg',
      description: 'I worked on Henderson Oil\'s website from post-design to project completion. The website is based in Joomla 1.5 and is fairly uncomplicated.',
      company: 'With a tradition that spans over three quarters of a century, Henderson Oil Company, Inc. continues to be a steady provider of the energy that runs our businesses, transportation, and homes. We provide a variety of fuel options, including branded and unbranded gasoline for dealers, heating oil for homes, bulk motor oils for commercial and industrial needs, and fleet fueling at our 24-hour cardlock fleet fueling center.',
      skills: ['xHTML', 'CSS', 'PHP', 'MySQL', 'Joomla 1.5'],
    },
  ];

  public get(): Observable<Project[]> {
    return of(this.projects);
  }

  public getLatest(): Observable<Project[]> {
    return this.get().pipe(
      map((projects) => projects.slice(0, 6)),
    );
  }

  public getItem(uri: string): Observable<Project> {
    return this.get().pipe(
      map((projects) => projects.find((project) => project.uri === uri) || nullProject),
    );
  }
}
